// Property catalogue for Third Rock Realty.
// Mohali/Tricity sector references; prices indicative of the 2026 market.
window.TR_PROPERTIES = window.RS_PROPERTIES = [
  {
    id: "p01",
    code: "TRR-2401",
    title: "4 BHK Independent Kothi",
    type: "Residential",
    subType: "Kothi",
    locality: "Sector 91, Mohali",
    plotSize: "500 Sq. Yd.",
    builtUp: "5,400 Sq. Ft.",
    bedrooms: 4,
    bathrooms: 5,
    facing: "North-East",
    parking: 3,
    furnishing: "Semi-furnished",
    age: "3 years",
    floor: "G + 2",
    status: "Ready to move",
    price: "₹ 3.85 Cr",
    pricePerSqft: "₹ 7,130 / Sq. Ft.",
    listingDate: "12 Apr 2026",
    rera: "PBRERA-SAS80-PR0421",
    tags: ["Park Facing", "Corner", "Vaastu"],
    summary:
      "A monolithic stone-clad kothi on a quiet park-facing road. Triple-height foyer, oak floors on bedrooms, modular Häcker kitchen, and a back lawn screened by ficus.",
    detail:
      "Built by the original owner in 2023, the house sits on a 500 sq. yd. corner plot facing the green belt. Ground floor opens through a 12-ft pivot door into a triple-height foyer with travertine inlay. The drawing and dining are split by a low-profile gas fireplace. Kitchen is full Häcker with Miele appliances and a pantry. Master suite on first floor has its own balcony over the park. Servant quarter and stilt parking for three cars at the rear.",
    hero: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["Modular kitchen", "Servant quarter", "Power back-up", "RO water", "CCTV", "Lift-ready shaft"],
  },
  {
    id: "p02",
    code: "TRR-2402",
    title: "Commercial SCO — Corner",
    type: "Commercial",
    subType: "SCO",
    locality: "Sector 70, Mohali",
    plotSize: "250 Sq. Yd.",
    builtUp: "3,600 Sq. Ft.",
    bedrooms: null,
    bathrooms: 4,
    facing: "South",
    parking: "Front + rear",
    furnishing: "Bare-shell",
    age: "8 years",
    floor: "G + 3",
    status: "Tenanted — ₹ 1.85 L / month",
    price: "₹ 5.40 Cr",
    pricePerSqft: "₹ 15,000 / Sq. Ft.",
    listingDate: "21 Mar 2026",
    rera: "PBRERA-SAS70-PR0118",
    tags: ["Corner", "Main Road", "Rented"],
    summary:
      "A four-storey SCO on the main 100-ft road, prime commercial location. Anchor tenant on ground; upper floors leased to a CA firm.",
    detail:
      "One of the better-located SCOs in the Sector 70 commercial belt — corner unit, double frontage, and 100-ft road in front. Ground floor leased to a retail brand (5+5 lock-in remaining), first floor to a chartered accountancy firm, second floor vacant and ready to fit-out, terrace rights with the unit. GMADA-approved, no encumbrance, electricity load of 22 KW sanctioned.",
    hero: "https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["Lift", "DG back-up", "Front parking", "Signage rights", "22 KW load"],
  },
  {
    id: "p03",
    code: "TRR-2403",
    title: "3 BHK Apartment",
    type: "Residential",
    subType: "Apartment",
    locality: "Sector 79, Mohali",
    plotSize: "—",
    builtUp: "1,820 Sq. Ft.",
    bedrooms: 3,
    bathrooms: 3,
    facing: "East",
    parking: 1,
    furnishing: "Unfurnished",
    age: "New",
    floor: "9 of 14",
    status: "Ready to move",
    price: "₹ 1.42 Cr",
    pricePerSqft: "₹ 7,800 / Sq. Ft.",
    listingDate: "02 May 2026",
    rera: "PBRERA-SAS79-PR0612",
    tags: ["High Floor", "Club", "Lift"],
    summary:
      "High-floor 3 BHK in a gated society with full club, two-tier security and a 65-ft frontage road. Walk to the upcoming metro alignment.",
    detail:
      "South-east corner unit on the 9th floor — sectional kitchen, three balconies, master with walk-in. The complex has a 35,000 sq. ft. club with pool, indoor games, gym, banquet, and an EV-ready basement. Possession is immediate; original allottee, single owner.",
    hero: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["Club & Pool", "Gym", "2-Tier Security", "EV Charging", "Power back-up"],
  },
  {
    id: "p04",
    code: "TRR-2404",
    title: "200 Sq. Yd. Residential Plot",
    type: "Plot",
    subType: "Residential Plot",
    locality: "Sector 88, JLPL Mohali",
    plotSize: "200 Sq. Yd.",
    builtUp: "—",
    bedrooms: null,
    bathrooms: null,
    facing: "North",
    parking: "—",
    furnishing: "—",
    age: "—",
    floor: "—",
    status: "Possession-ready",
    price: "₹ 1.55 Cr",
    pricePerSqft: "₹ 86,000 / Sq. Yd.",
    listingDate: "28 Feb 2026",
    rera: "PBRERA-SAS88-PR0277",
    tags: ["GMADA", "JLPL", "Park Side"],
    summary:
      "North-facing 200 sq. yd. plot in JLPL Sector 88, two plots from the pocket park. Clean title, all dues paid.",
    detail:
      "Allotted in the JLPL Industrial-cum-Residential scheme. 200 sq. yd., 30 ft. front × 60 ft. depth, possession letter issued. Sector 88 has the highest absorption in JLPL over the last 18 months — plot prices have risen 22% YoY. Build coverage 65%, FAR 1.75, three habitable floors plus stilt allowed.",
    hero: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["GMADA approved", "All dues cleared", "Sector park adj.", "60 ft. road"],
  },
  {
    id: "p05",
    code: "TRR-2405",
    title: "Showroom on 200-ft Road",
    type: "Commercial",
    subType: "Showroom",
    locality: "Aerocity, Mohali",
    plotSize: "300 Sq. Yd.",
    builtUp: "5,200 Sq. Ft.",
    bedrooms: null,
    bathrooms: 4,
    facing: "West",
    parking: "Front",
    furnishing: "Bare-shell",
    age: "New",
    floor: "G + 2",
    status: "Vacant",
    price: "₹ 6.20 Cr",
    pricePerSqft: "₹ 11,920 / Sq. Ft.",
    listingDate: "10 Mar 2026",
    rera: "PBRERA-SAS-AC-PR0095",
    tags: ["Highway", "Showroom", "Corner"],
    summary:
      "Bare-shell showroom on the 200-ft Aerocity main artery. Glass frontage of 45 ft. Ideal for an automobile or furniture brand.",
    detail:
      "GMADA Aerocity, plot category SCO-XL. 45 ft. of uninterrupted glass frontage, 28 ft. floor-to-floor on ground, internal staircase plus provision for a customer lift. Power load 35 KW sanctioned. Walk to the upcoming international airport interchange. Vacant — owner open to a 9-year lease at ₹ 4.5 L / month or outright sale.",
    hero: "https://images.unsplash.com/photo-1577412647305-991150c7d163?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1604328698692-f76ea9498e76?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["45 ft. frontage", "Lift shaft", "35 KW load", "Highway facing"],
  },
  {
    id: "p06",
    code: "TRR-2406",
    title: "2 BHK Builder Floor",
    type: "Residential",
    subType: "Builder Floor",
    locality: "Sector 67, Mohali",
    plotSize: "—",
    builtUp: "1,150 Sq. Ft.",
    bedrooms: 2,
    bathrooms: 2,
    facing: "South-West",
    parking: 1,
    furnishing: "Semi-furnished",
    age: "5 years",
    floor: "2 of 3",
    status: "Vacant",
    price: "₹ 78 L",
    pricePerSqft: "₹ 6,780 / Sq. Ft.",
    listingDate: "05 Apr 2026",
    rera: "PBRERA-SAS67-PR0334",
    tags: ["End Unit", "Stilt Parking", "Wooden Floor"],
    summary:
      "Quiet 2 BHK builder floor a five-minute walk from the Phase 11 market. Independent staircase, no maintenance.",
    detail:
      "Second-floor unit of a three-storey builder block. Two bedrooms, one with attached balcony; large living-dining; modular kitchen with hob and chimney. Wooden flooring in bedrooms, vitrified tiles elsewhere. Inverter back-up, RO, geysers and ACs included. One stilt parking + visitor space.",
    hero: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["Modular kitchen", "Inverter", "ACs included", "Independent entry"],
  },
  {
    id: "p07",
    code: "TRR-2407",
    title: "Industrial Plot — JLPL",
    type: "Plot",
    subType: "Industrial Plot",
    locality: "Sector 82, JLPL Mohali",
    plotSize: "1,000 Sq. Yd.",
    builtUp: "—",
    bedrooms: null,
    bathrooms: null,
    facing: "East",
    parking: "—",
    furnishing: "—",
    age: "—",
    floor: "—",
    status: "Land use change pending",
    price: "₹ 7.40 Cr",
    pricePerSqft: "₹ 74,000 / Sq. Yd.",
    listingDate: "17 Jan 2026",
    rera: "PBRERA-SAS82-IND0019",
    tags: ["Industrial", "IT/ITES Permitted", "1000 Sq. Yd."],
    summary:
      "1,000 sq. yd. industrial plot in JLPL Sector 82. IT/ITES permitted use, three-side open, near the Eicher campus.",
    detail:
      "Allottee plot in the JLPL Industrial Estate. Three-side open, immediate next to the Eicher Goodearth campus. Permissible use includes IT/ITES, light manufacturing, warehousing. Build coverage 60%, FAR 1.65. Application for CLU (commercial land use) to office park is under process — papers will be transferred on signing.",
    hero: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["Three-side open", "IT/ITES use", "All dues paid", "Wide internal road"],
  },
  {
    id: "p08",
    code: "TRR-2408",
    title: "Penthouse — Duplex 4 BHK",
    type: "Residential",
    subType: "Penthouse",
    locality: "Sector 66-A, Mohali",
    plotSize: "—",
    builtUp: "3,950 Sq. Ft.",
    bedrooms: 4,
    bathrooms: 5,
    facing: "North",
    parking: 2,
    furnishing: "Fully-furnished",
    age: "2 years",
    floor: "12-13 of 13",
    status: "Vacant",
    price: "₹ 3.20 Cr",
    pricePerSqft: "₹ 8,100 / Sq. Ft.",
    listingDate: "19 Mar 2026",
    rera: "PBRERA-SAS66-PR0211",
    tags: ["Duplex", "Private Terrace", "Furnished"],
    summary:
      "Top-floor duplex penthouse with a 1,200 sq. ft. private terrace and uninterrupted Shivalik view on a clear day.",
    detail:
      "Spans the top two floors. Lower level — drawing, dining, family lounge, guest bedroom, kitchen and powder. Upper level — master, two children's rooms, study, and a 1,200 sq. ft. private terrace with deck flooring, pergola, and a wet bar. Fully furnished with Italian sofas, Häcker kitchen, Bosch appliances, smart lighting throughout.",
    hero: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: ["Private terrace", "Smart home", "2 reserved parkings", "Concierge"],
  },
  { id:"p09", code:"TRR-2409", title:"3 BHK Apartment", type:"Residential", subType:"Apartment", locality:"Sector 17, Chandigarh", plotSize:"—", builtUp:"1,950 Sq. Ft.", bedrooms:3, bathrooms:3, facing:"East", parking:2, furnishing:"Semi-furnished", age:"5 years", floor:"7 of 14", status:"Vacant", price:"₹ 2.20 Cr", pricePerSqft:"₹ 11,280 / Sq. Ft.", listingDate:"02 Jun 2026", rera:"PBRERA-CHD17-PR0312", tags:["City Centre","Lift","Power back-up"], summary:"Centrally located 3BR apartment in the heart of Chandigarh's commercial core.", detail:"Walking distance to Sector 17 plaza. Spacious living-dining, modular kitchen, three bedrooms with attached baths. Two reserved parkings.", hero:"https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Lift","Power back-up","Reserved parking","CCTV"] },
  { id:"p10", code:"TRR-2410", title:"4 BHK Independent Villa", type:"Residential", subType:"Kothi", locality:"Sector 9, Chandigarh", plotSize:"1 Kanal", builtUp:"6,800 Sq. Ft.", bedrooms:4, bathrooms:5, facing:"North-East", parking:4, furnishing:"Unfurnished", age:"12 years", floor:"G + 1", status:"Ready to move", price:"₹ 9.50 Cr", pricePerSqft:"₹ 13,970 / Sq. Ft.", listingDate:"24 May 2026", rera:"—", tags:["Sector 9","1 Kanal","Heritage"], summary:"Heritage-side 1-Kanal kothi in one of Chandigarh's oldest sectors.", detail:"Original Le Corbusier-grid kothi with mature trees and a wide front lawn. Three sides open. Excellent for end-use buyer or boutique office conversion (subject to estate office approval).", hero:"https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["1 Kanal","Mature garden","Servant quarter","Three-side open"] },
  { id:"p11", code:"TRR-2411", title:"Commercial Showroom", type:"Commercial", subType:"Showroom", locality:"VIP Road, Zirakpur", plotSize:"180 Sq. Yd.", builtUp:"4,200 Sq. Ft.", bedrooms:null, bathrooms:3, facing:"North", parking:"Front", furnishing:"Bare-shell", age:"6 years", floor:"G + 2", status:"Tenanted — ₹ 1.45 L / mo", price:"₹ 4.80 Cr", pricePerSqft:"₹ 11,430 / Sq. Ft.", listingDate:"18 May 2026", rera:"—", tags:["Highway-facing","Tenanted","High-footfall"], summary:"Highway-facing showroom on Zirakpur's main commercial spine with anchor tenant in place.", detail:"Triple-floor showroom currently tenanted to a national brand on a 9-year lease. Yields ~4.1% net. Front and rear loading.", hero:"https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Highway frontage","Anchor tenant","Rear loading"] },
  { id:"p12", code:"TRR-2412", title:"250 Sq. Yd. Residential Plot", type:"Plot", subType:"Residential Plot", locality:"Sector 124, Kharar", plotSize:"250 Sq. Yd.", builtUp:"—", bedrooms:null, bathrooms:null, facing:"East", parking:"—", furnishing:"—", age:"—", floor:"—", status:"Ready to construct", price:"₹ 88 Lakh", pricePerSqft:"—", listingDate:"08 May 2026", rera:"PBRERA-KHR124-PR0114", tags:["GMADA","East-facing","Park-side"], summary:"GMADA-allotted park-side plot in the fastest-growing Kharar pocket.", detail:"Park-facing, east-facing 250 sq. yd. plot. All dues clear, mutation in place. Ready for sanction.", hero:"https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Park-facing","All dues paid","Wide internal road"] },
  { id:"p13", code:"TRR-2413", title:"5 BHK Builder Floor", type:"Residential", subType:"Builder Floor", locality:"Sector 88, Mohali", plotSize:"400 Sq. Yd.", builtUp:"3,800 Sq. Ft.", bedrooms:5, bathrooms:5, facing:"West", parking:2, furnishing:"Semi-furnished", age:"1 year", floor:"1 of 4", status:"Vacant", price:"₹ 2.45 Cr", pricePerSqft:"₹ 6,450 / Sq. Ft.", listingDate:"30 Apr 2026", rera:"PBRERA-SAS88-PR0508", tags:["New build","Modular","Lift-ready"], summary:"New-build 5BR builder floor with all premium fittings already in place.", detail:"Brand new first floor with separate entry. Five bedrooms with walk-in wardrobes, modular kitchen, two reserved parkings.", hero:"https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Modular kitchen","Walk-in wardrobes","Lift shaft"] },
  { id:"p14", code:"TRR-2414", title:"2 BHK Apartment", type:"Residential", subType:"Apartment", locality:"VIP Road, Zirakpur", plotSize:"—", builtUp:"1,250 Sq. Ft.", bedrooms:2, bathrooms:2, facing:"North", parking:1, furnishing:"Fully-furnished", age:"4 years", floor:"5 of 11", status:"Tenanted — ₹ 28 K / mo", price:"₹ 78 Lakh", pricePerSqft:"₹ 6,240 / Sq. Ft.", listingDate:"22 Apr 2026", rera:"PBRERA-ZRK-PR0207", tags:["Investor pick","Furnished","Rented"], summary:"Investor-friendly 2BR apartment with tenant in place from day one.", detail:"Compact, well-laid out 2BR in a gated society. Yields ~4.3% net. Tenanted to a corporate professional.", hero:"https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Gated society","Swimming pool","Power back-up"] },
  { id:"p15", code:"TRR-2415", title:"Office Space — Bare-shell", type:"Commercial", subType:"Office", locality:"IT City, Sector 66B, Mohali", plotSize:"—", builtUp:"2,800 Sq. Ft.", bedrooms:null, bathrooms:2, facing:"South-East", parking:3, furnishing:"Bare-shell", age:"3 years", floor:"4 of 8", status:"Vacant", price:"₹ 2.10 Cr", pricePerSqft:"₹ 7,500 / Sq. Ft.", listingDate:"15 Apr 2026", rera:"PBRERA-SAS66B-PR0306", tags:["IT corridor","Bare-shell","Reserved parking"], summary:"Bare-shell office space in the Mohali IT corridor, ready for fit-out.", detail:"Floor plate in a Grade-A IT building. Three reserved parkings, 100% power back-up, central HVAC.", hero:"https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Central HVAC","Power back-up","DG redundancy","Cafeteria"] },
  { id:"p16", code:"TRR-2416", title:"500 Sq. Yd. Plot", type:"Plot", subType:"Residential Plot", locality:"Sector 99, Mohali", plotSize:"500 Sq. Yd.", builtUp:"—", bedrooms:null, bathrooms:null, facing:"North", parking:"—", furnishing:"—", age:"—", floor:"—", status:"Ready to construct", price:"₹ 2.65 Cr", pricePerSqft:"—", listingDate:"10 Apr 2026", rera:"PBRERA-SAS99-PR0419", tags:["Wide road","Corner","JLPL"], summary:"Corner JLPL plot on a 60-ft wide road. Three-side open, north-facing.", detail:"Premium corner plot. Allotment, mutation and all dues complete. Sanction-ready.", hero:"https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Corner","Three-side open","Wide road"] },
  { id:"p17", code:"TRR-2417", title:"Premium 3 BHK Apartment", type:"Residential", subType:"Apartment", locality:"New Chandigarh, Aerocity-adjacent", plotSize:"—", builtUp:"2,100 Sq. Ft.", bedrooms:3, bathrooms:3, facing:"South", parking:2, furnishing:"Semi-furnished", age:"New build", floor:"15 of 22", status:"Ready to move", price:"₹ 1.85 Cr", pricePerSqft:"₹ 8,810 / Sq. Ft.", listingDate:"05 Apr 2026", rera:"PBRERA-NCH-PR0612", tags:["High-floor","New build","Clubhouse"], summary:"High-floor 3BR in a master-planned New Chandigarh tower with full amenities.", detail:"15th-floor unit, Shivalik view. Clubhouse, pool, gym, kids' play area, 24×7 security. Two reserved parkings.", hero:"https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Clubhouse","Swimming pool","Gym","CCTV"] },
  { id:"p18", code:"TRR-2418", title:"3 BHK Kothi — Resale", type:"Residential", subType:"Kothi", locality:"Sector 21, Panchkula", plotSize:"300 Sq. Yd.", builtUp:"3,200 Sq. Ft.", bedrooms:3, bathrooms:4, facing:"East", parking:2, furnishing:"Unfurnished", age:"15 years", floor:"G + 1", status:"Ready to move", price:"₹ 2.95 Cr", pricePerSqft:"₹ 9,220 / Sq. Ft.", listingDate:"28 Mar 2026", rera:"—", tags:["Park-facing","Quiet sector","Resale"], summary:"Park-facing resale kothi in one of Panchkula's quietest residential sectors.", detail:"East-facing, park-side, 300 sq yd plot. Original owner. Well-maintained, ready for either end-use or modernisation.", hero:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Park-facing","Servant quarter","Three-side open"] },
  { id:"p19", code:"TRR-2419", title:"SCO — Corner", type:"Commercial", subType:"SCO", locality:"Sector 82, JLPL Mohali", plotSize:"200 Sq. Yd.", builtUp:"3,200 Sq. Ft.", bedrooms:null, bathrooms:3, facing:"East", parking:"Front + rear", furnishing:"Bare-shell", age:"5 years", floor:"G + 2", status:"Vacant", price:"₹ 4.20 Cr", pricePerSqft:"₹ 13,125 / Sq. Ft.", listingDate:"20 Mar 2026", rera:"PBRERA-SAS82-PR0726", tags:["Corner","High-footfall","SCO"], summary:"Corner SCO at the JLPL commercial junction with vacant possession.", detail:"Three-storey SCO with bare-shell interiors. Front and rear access. Approved for retail and office mixed use.", hero:"https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Corner","Two frontages","Lift-ready"] },
  { id:"p20", code:"TRR-2420", title:"200 Sq. Yd. Plot", type:"Plot", subType:"Residential Plot", locality:"Aerocity, Mohali", plotSize:"200 Sq. Yd.", builtUp:"—", bedrooms:null, bathrooms:null, facing:"West", parking:"—", furnishing:"—", age:"—", floor:"—", status:"Ready to construct", price:"₹ 1.25 Cr", pricePerSqft:"—", listingDate:"15 Mar 2026", rera:"PBRERA-AER-PR0234", tags:["Aerocity","Airport-side","GMADA"], summary:"GMADA Aerocity plot, walking distance to the international terminal road.", detail:"Allotted by GMADA, all dues paid, mutation done. Excellent connectivity to airport and Chandigarh.", hero:"https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Airport-side","All dues paid","Wide internal road"] },
  { id:"p21", code:"TRR-2421", title:"4 BHK Apartment — Premium", type:"Residential", subType:"Apartment", locality:"Sector 20, Panchkula", plotSize:"—", builtUp:"2,650 Sq. Ft.", bedrooms:4, bathrooms:4, facing:"North", parking:2, furnishing:"Fully-furnished", age:"3 years", floor:"9 of 16", status:"Vacant", price:"₹ 2.85 Cr", pricePerSqft:"₹ 10,750 / Sq. Ft.", listingDate:"08 Mar 2026", rera:"PBRERA-PKL20-PR0419", tags:["Premium","Furnished","High-floor"], summary:"Fully-furnished premium 4BR in a gated Panchkula complex with full amenities.", detail:"Ninth-floor 4BR with Italian-furnished interiors, modular kitchen with appliances, two reserved parkings. Clubhouse, gym, pool.", hero:"https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Fully furnished","Clubhouse","Pool","Gym"] },
  { id:"p22", code:"TRR-2422", title:"6 BHK Kothi — Estate", type:"Residential", subType:"Kothi", locality:"Sector 8, Chandigarh", plotSize:"2 Kanal", builtUp:"12,000 Sq. Ft.", bedrooms:6, bathrooms:7, facing:"East", parking:6, furnishing:"Unfurnished", age:"20 years", floor:"G + 1", status:"Ready to move", price:"₹ 22.50 Cr", pricePerSqft:"₹ 18,750 / Sq. Ft.", listingDate:"25 Feb 2026", rera:"—", tags:["2 Kanal","Estate","Heritage sector"], summary:"Estate-grade 2-Kanal kothi in Chandigarh's most prestigious residential sector.", detail:"East-facing, 2-Kanal plot, six bedrooms, two drawing rooms, formal dining, library, home theatre, staff quarters. Mature garden on three sides.", hero:"https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["2 Kanal","Library","Home theatre","Staff quarters"] },
  { id:"p23", code:"TRR-2423", title:"3 BHK Builder Floor", type:"Residential", subType:"Builder Floor", locality:"Sector 70, Mohali", plotSize:"250 Sq. Yd.", builtUp:"2,000 Sq. Ft.", bedrooms:3, bathrooms:3, facing:"South", parking:1, furnishing:"Semi-furnished", age:"2 years", floor:"2 of 3", status:"Vacant", price:"₹ 1.35 Cr", pricePerSqft:"₹ 6,750 / Sq. Ft.", listingDate:"18 Feb 2026", rera:"PBRERA-SAS70-PR0511", tags:["Lift","Quiet","Family"], summary:"Quiet residential pocket, lift-served 3BR builder floor.", detail:"Second-floor unit with private entry. Modular kitchen, semi-furnished bedrooms, one covered parking, lift access.", hero:"https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Lift","Reserved parking","Modular kitchen"] },
  { id:"p24", code:"TRR-2424", title:"Commercial Office — Furnished", type:"Commercial", subType:"Office", locality:"Sector 17, Chandigarh", plotSize:"—", builtUp:"1,800 Sq. Ft.", bedrooms:null, bathrooms:2, facing:"East", parking:2, furnishing:"Fully-furnished", age:"4 years", floor:"3 of 5", status:"Tenanted — ₹ 1.20 L / mo", price:"₹ 2.40 Cr", pricePerSqft:"₹ 13,330 / Sq. Ft.", listingDate:"10 Feb 2026", rera:"—", tags:["Sector 17","Furnished","Yields 6%"], summary:"Fully-furnished CBD office in Sector 17 with stable tenant in place.", detail:"Twelve cabins, conference room, reception, pantry. Currently leased to a law firm on a 5-year lease.", hero:"https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Furnished","Lift","Reserved parking"] },
  { id:"p25", code:"TRR-2425", title:"Industrial Plot — JLPL", type:"Plot", subType:"Industrial Plot", locality:"Sector 82A, JLPL Mohali", plotSize:"1,000 Sq. Yd.", builtUp:"—", bedrooms:null, bathrooms:null, facing:"North", parking:"—", furnishing:"—", age:"—", floor:"—", status:"Ready to construct", price:"₹ 3.40 Cr", pricePerSqft:"—", listingDate:"02 Feb 2026", rera:"—", tags:["Industrial","IT/ITES","JLPL"], summary:"Thousand-yard industrial plot in JLPL's IT/ITES extension.", detail:"Wide internal road, all utilities at plot. Approved for IT/ITES use. All dues paid.", hero:"https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["IT/ITES use","Wide road","Utilities at plot"] },
  { id:"p26", code:"TRR-2426", title:"2 BHK Apartment — New", type:"Residential", subType:"Apartment", locality:"Sector 117, Kharar", plotSize:"—", builtUp:"1,150 Sq. Ft.", bedrooms:2, bathrooms:2, facing:"East", parking:1, furnishing:"Semi-furnished", age:"New build", floor:"8 of 18", status:"Vacant", price:"₹ 62 Lakh", pricePerSqft:"₹ 5,390 / Sq. Ft.", listingDate:"25 Jan 2026", rera:"PBRERA-KHR117-PR0322", tags:["Entry-level","New build","Clubhouse"], summary:"Entry-level 2BR in a new master-planned Kharar township.", detail:"East-facing 2BR, eighth floor, township amenities. Best value pickup for first-time buyers.", hero:"https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Clubhouse","Pool","Power back-up"] },
  { id:"p27", code:"TRR-2427", title:"Boutique Showroom — Aerocity", type:"Commercial", subType:"Showroom", locality:"Aerocity, Mohali", plotSize:"200 Sq. Yd.", builtUp:"4,400 Sq. Ft.", bedrooms:null, bathrooms:3, facing:"South", parking:"Front + rear", furnishing:"Bare-shell", age:"2 years", floor:"G + 2", status:"Vacant", price:"₹ 5.60 Cr", pricePerSqft:"₹ 12,730 / Sq. Ft.", listingDate:"18 Jan 2026", rera:"PBRERA-AER-PR0712", tags:["Aerocity","High-visibility","Bare-shell"], summary:"High-visibility boutique showroom on Aerocity's main commercial spine.", detail:"Three-storey showroom on the front row. Excellent for boutique retail, F&B or experience centre.", hero:"https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Front row","Two frontages","Rear loading"] },
  { id:"p28", code:"TRR-2428", title:"400 Sq. Yd. Corner Plot", type:"Plot", subType:"Residential Plot", locality:"New Chandigarh", plotSize:"400 Sq. Yd.", builtUp:"—", bedrooms:null, bathrooms:null, facing:"South-East", parking:"—", furnishing:"—", age:"—", floor:"—", status:"Ready to construct", price:"₹ 1.95 Cr", pricePerSqft:"—", listingDate:"10 Jan 2026", rera:"PBRERA-NCH-PR0419", tags:["Corner","Park-facing","New Chandigarh"], summary:"Corner park-facing plot in the New Chandigarh master plan.", detail:"South-east facing corner, park on one side, 60-ft wide internal road. Allotment and mutation complete.", hero:"https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80", gallery:[], amenities:["Corner","Park-facing","All dues paid"] },
];
